### ISSUE TITLE
Project Page - Some user facing issue of loading in project page By CA Kamlesh Kumar

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1797]
**Describe the bug** 
- Some user when loged in there project page is not loading in one pc
https://www.berrycast.com/conversations/36278f5b-b180-504e-9b54-98e9b054c6d5

**Comment by Avinash-ecb** [comment]
I contact them to check the issue they are not free that time so they will call when they are free
Kamlesh Kumar contact no. Phone

**Comment by mitulpanch** [comment]
Token Expiry is problem ,on particular pc, we are not getting same error anywhere else,
So will try to mitigate according to particular PC

Technical detail

Token expiry is setting is Local and Date.now() is setting in UTC that makes token always expired,
On each page reload token is set to reset due to above error
