### ISSUE TITLE
Accounts requirement by Sirvi sir

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#334]
<img width="1280" alt="111447405-6a36f300-8733-11eb-8924-2882b7b36547" src="https://user-images.githubusercontent.com/46882964/112185452-3de51000-8c26-11eb-8c8e-b5127ba227ba.png">
<img width="1280" alt="111447432-70c56a80-8733-11eb-9d17-9225122b76d8" src="https://user-images.githubusercontent.com/46882964/112185477-43daf100-8c26-11eb-822d-23e3c32f8cc7.png">

**Comment by mitulpanch** [comment]
@vinpahilwani  Approve jo bhi chahiye,or nahi chahiye

**Comment by vinpahilwani** [comment]
1st image - 1. voucher number is available in expand and i dont see what value it will bring if we show outside and it will make screen messy if we show that 
2. unbilled- already done
3. email selected vouchers- possible but it will shoot multiple emails. seperate email for each voucher which i think is not suitable. instead of that you can send email of entire ledger which we are doing

2nd image
1. voucher number and reference number - it is already clickable so one can access info on click if they wish to
2. send email- we can definetly provide email to send single voucher but let me discuss with sirvi first
